# Generated by Django 3.2 on 2021-05-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alllisting',
            new_name='allitems',
        ),
    ]
